# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name=b'email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name=b'first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name=b'last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name=b'date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'active')),
                ('age', models.PositiveIntegerField(default=21, verbose_name=b'age')),
                ('start_date_of_work', models.DateField(auto_now_add=True, verbose_name=b'start date of work')),
                ('role', models.CharField(choices=[(b'director', b'Director'), (b'qa', b'Quality assurance'), (b'developer', b'Developer'), (b'manager', b'Office manager'), (b'designer', b'Designer')], default=b'developer', max_length=100, verbose_name=b'role employee')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name=b'middle name')),
                ('is_admin', models.BooleanField(default=False, verbose_name=b'staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
